#!/usr/bin/python

import os

for a in range(16):
	a=str(a)
	if a!="0":
		print "vboxmanage hostonlyif remove vboxnet"+a
		os.system("vboxmanage hostonlyif remove vboxnet"+a+" 2>output34.txt")


exit()
