#!/usr/bin/python
# sudo ./test 25 99 pollo pato a b c d e

import os
import re
import subprocess
import sys

host_ip=sys.argv[1]
guest_ip=sys.argv[2]
vm_name=sys.argv[3]
snapshot_name=sys.argv[4]
tag_list=""
for arg in sys.argv[5::]:
	if arg==sys.argv[5]: #To avoid having a comma at the beggining
		tag_list=arg
	else:
		tag_list=tag_list+','+arg

##### cuckoo.conf #####
options_list=[["machinery = ","virtualbox"],["memory_dump = ","on"],["ip = ",host_ip],["port = ","2042"]]
line_written=False
ip_written=False
port_written=False

#Opening the file for reading and writting
conf_file=open('cuckoo-original/conf/cuckoo.conf', 'r+')
tmp_file=open('/tmp/cuckoo-tmp.conf', 'w+')

line=conf_file.readline()
while line!="":
	print line
	for option in options_list:
		try:	
			print option[0]
			re.search(option[0], line).group(0)
			tmp_file.write(option[0]+option[1]+'\n')
			line_written=True
			break

		except: #if the search fails, it's because there's not such a string
			pass	

	if not line_written:
		tmp_file.write(line)
	line=conf_file.readline()
	line_written=False

conf_file.close()
tmp_file.close()

# Open truncate file, we are going to fill it with the tmp one
conf_file=open('cuckoo/conf/cuckoo2.conf', 'w') 
tmp_file=open('/tmp/cuckoo-tmp.conf', 'r')

new_content=tmp_file.read()
conf_file.write(new_content)

conf_file.close()
tmp_file.close()


